### ISSUE TITLE
Why is there a package.json/node.js for a "Golang TCP proxy"?

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-incubator/switchboard#5]

**Comment by robdimsdale** [comment]
Because we use node.js to package up the static html for the UI during development; we then check those files in to /static. Node does not run on either the compilation VM or the job VM - it's only used in development.

**Comment by drnic** [comment]
Oh, there's a UI for a TCP proxy? Is it an haproxy-esque UI for admins?

**Comment by robdimsdale** [comment]
Yes. It's a Pivotal-UI-branded dashboard for an operator to see the proxy's view of the available backends, their health, and which backend sessions are currently being routed to. It's still in development at the moment.

**Comment by drnic** [comment]
Ok, thanks.

Why "Pivotal-UI-branded" for a @cloudfoundry-incubator project? Perhaps start with a CF theme instead?

**Comment by robdimsdale** [comment]
I don't have an answer to that. Perhaps @shalako does?

**Comment by shalako** [comment]
We don't have a CF theme yet. Designers are looking into a UI framework that supports white-labeling. For now, consider it a default; operators can replace the skin of the UI with their own. 

As Rob said, it's still in development.
