### ISSUE TITLE
README section: Why switchboard vs haproxy vs nginx

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-incubator/switchboard#6]
In the spirit of Hashicorp explaining why to use one of their projects vs existing possible solutions, could we add a section to the README about what Switchboard will do, and how it is better and/or where to use it instead of haproxy/nginx/whatever?

**Comment by robdimsdale** [comment]
That sounds like a reasonable request. I would expect we would want to provide that information.

FYI I provided a brief answer to 'why does switchboard exist' in [this issue](https://github.com/cloudfoundry-incubator/switchboard/issues/1) but in essence we want to proxy long-lived TCP connections between a client and a backend, and sever them when the backend reports unhealthy, even it is still accessible. No available product provides this functionality.

**Comment by drnic** [comment]
Thx for link.

**Comment by shalako** [comment]
I updated REAME with a link to develop branch of cf-mysql-release. We can keep this one open to improve our README as development proceeds.

**Comment by menicosia** [comment]
Fixed in [README.md](https://github.com/cloudfoundry-incubator/switchboard/blob/master/README.md). Closing issue, but as always, feel free to re-open if you think something would be lost.

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.
