### ISSUE TITLE
Are you doing some probing on the incomming connections?

### ISSUE THREAD

**Issue by elico** [cloudfoundry-incubator/switchboard#9]
Are you doing some probing on the incomming connections? if so can I get a pointer in the code?
I am looking at different ways that proxy applications are identifying incoming connections.
How do they verify that it's HTTP or TLS or other?

**Comment by robdimsdale** [comment]
Currently we don't do any inspection on the incoming connections. Bytes are copied bidirectionally with no awareness of contents.

All data connections arriving at the proxy are TCP (TLS termination is expected to have happened upstream) and the control-path connections are HTTP (again, HTTPS termination is expected to have happened upstream, and set the `X-Forwarded-Proto: https` header).

Does this answer your question?

**Comment by elico** [comment]
@robdimsdale yes! Thanks!

**Comment by robdimsdale** [comment]
Great, thanks.
